# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbe610ad1308ab357c86be4db0dbc40c53606b9592058de0659dd2114cc68995daab412ce88eae7b9acf73ce9ee6799663e09fa4c7198def3f67e35a16b2de65

test:
  secret_key_base: c2a5de1002a92908fd4642c3f55ce588390bbee42e3e658519fd5d792ec7c5b2c1e5e102c701f4bd90387e7781b324bee1de0709978eb8ced37e2471c88173f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
